library(reticulate)
my_module <- source_python("../imputation_code/autoencoder.py")

mcar_10 <- read.csv('../../data/MCAR/mcar10/mcar_10.csv', row.names = 1)
mcar_25 <- read.csv('../../data/MCAR/mcar25/mcar_25.csv', row.names = 1)
mcar_40 <- read.csv('../../data/MCAR/mcar40/mcar_40.csv', row.names = 1)
mnar_30 <- read.csv('../../data/MNAR/mnar30/mnar_30.csv', row.names = 1)
mnar_50 <- read.csv('../../data/MNAR/mnar50/mnar_50.csv', row.names = 1)
mcar_path <- read.csv('../../data/path/mcar_40/path_mcar_40.csv', row.names = 1)
mnar_path <- read.csv('../../data/path/mnar_50/path_mnar_50.csv', row.names = 1)

mcar_10i <- na_autoencoder(mcar_10)
mcar_25i <- na_autoencoder(mcar_25)
mcar_40i <- na_autoencoder(mcar_40)
mnar_30i <- na_autoencoder(mnar_30)
mnar_50i <- na_autoencoder(mnar_50)
mcar_pathi <- na_autoencoder(mcar_path)
mnar_pathi <- na_autoencoder(mnar_path)

write.csv(mcar_10i, '../../data/MCAR/mcar10/ae_mcar_10.csv')
write.csv(mcar_25i, '../../data/MCAR/mcar25/ae_mcar_25.csv')
write.csv(mcar_40i, '../../data/MCAR/mcar40/ae_mcar_40.csv')
write.csv(mnar_30i, '../../data/MNAR/mnar30/ae_mnar_30.csv')
write.csv(mnar_50i, '../../data/MNAR/mnar50/ae_mnar_50.csv')
write.csv(mcar_pathi, '../../data/path/mcar_40/ae_path_mcar.csv')
write.csv(mnar_pathi, '../../data/path/mnar_50/ae_path_mnar.csv')
